### ISSUE TITLE
Would be nice to expose a function to get the EPL code.

### ISSUE THREAD

**Issue by robincsamuel** [wankdanker/node-epl#2]
Thanks for this package. I think it would be nice to expose a function to get the EPL output. We have a situation like storing the EPL or using it with other libs like `qz-tray`. 

Happy to make a PR if it sounds good :)

**Comment by wankdanker** [comment]
Hi @robincsamuel! The EPL output is available at `epl.output`.

example:

```js
const epl = require('epl')();
const output = epl.start()
      .drawBarcode('123456789999', 100, 4, true)
      .end()
      .output;
```

Is that good enough?

**Comment by robincsamuel** [comment]
That's great! I was overlooking for a function to give me the output :-D

Maybe, we can add this example to the readme. 

Thank you!
